import type { Metadata } from "next";
import Header from "./components/layout/Header";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";
import Footer from "./components/layout/Footer";
import { SessionProviders } from "./providers/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviders>
        <QueryProvider>
          <body className={` bg-black antialiased`}>
            <Header />
            {children}
            <Footer />
          </body>
        </QueryProvider>
      </SessionProviders>
    </html>
  );
}
