import type { Metadata } from "next";
import Header from "./components/layout/Header";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={` bg-black antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </QueryProvider>
    </html>
  );
}
